name: symphony
description: "An open source music player that contains the main local and offline features."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/symphony-mp/symphony_desktop

version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: ^3.35.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
